const ACTIONS = {
  setActiveTab: "SET_ACTIVE_TAB",
  getDoctors: "GET_DOCTORS",
  getDoctor: "GET_DOCTOR",
  getPatients: "GET_PATIENTS",
  getAppointments: "GET_APPOINTMENTS",
  getAppointment: "GET_APPOINTMENT",
  getAds: "GET_ADS",
  setAd: "SET_AD",
  setDoctor: "SET_DOCTOR",
  setUser: "SET_USER",
  logOut: "LOG_OUT",
  getBlogs: "GET_BLOGS",
  setBlog: "SET_BLOG",
  getPatientAlert: "GET_PATIENT_ALERTS",
  getDoctorAlert: "GET_DOCTOR_ALERTS",
  setAlert: "SET_ALERT",
  getReviews: "GET_REVIEWS",
  getReview: "GET_REVIEW",
  setDashboard: "SET_DASHBOARD",
};
export default ACTIONS;
